FROM ruby:alpine
RUN set -ex \
	\
	&& apk add --no-cache --virtual .ruby-builddeps \
	ruby \
  ruby-dev \
  ruby-bigdecimal \
  ruby-json \
  build-base\
  libssl1.0 \
  libc6-compat

ENV APP_HOME /app
RUN mkdir $APP_HOME

WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/
RUN bundle install
ADD . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
